# Generated by Django 5.0.6 on 2024-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_solutionresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionresult',
            name='executed_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
