# Generated by Django 5.0.6 on 2024-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_solutionresult_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionresult',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
